import type { Metadata } from 'next'
import { Acme, Roboto  } from 'next/font/google'
import './globals.css'
import Providers from '@/components/providers'

const roboto = Roboto({ 
  subsets: ['latin'] ,weight: ['100', '300', '400', '500', '700', '900'],
  display: "swap",
  variable: '--font-main',
  adjustFontFallback: false
})

const headingFont = Acme({ 
  subsets: ['latin'], weight: ["400"],
  display: "swap",
  variable: '--font-heading',
  adjustFontFallback: false
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${headingFont.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
